feat: render dei progetti pagina /progetti/
omardeangelis/hpv4learning pull request #107
Opened 2022-06-26 13:43 UTC by leonardodemarco00

## Done
- Renderizzato i progetti utilizzando ProjectSection

2022-06-26 15:00 UTC, omardeangelis requested changes

2022-06-26 15:00 UTC, omardeangelis commented on src/template/ProjectsHome.tsx
> +                    link={`/progetti/${post.fieldValue.toLowerCase()}/`}
Hai provato a lanciare `yarn lint --fix` ?  Sembra strano che non pianga qua

2022-06-26 15:00 UTC, omardeangelis commented on src/template/ProjectsHome.tsx
> +              <ProjectSection projects={post.nodes}></ProjectSection>
Hai provato a lanciare `yarn lint --fix` ?  Anche qua dovrebbe piangere al 100%

2022-06-26 15:15 UTC, omardeangelis requested changes

2022-06-26 15:15 UTC, omardeangelis commented on src/template/ProjectsHome.tsx
> +                  fontSize={{ xs: "20px", lg: "34px" }}
Questi devono essere degli H2 @leonardodemarco00

2022-06-27 19:00 UTC, omardeangelis commented
@leonardodemarco00 Risolvi tu i conflicts perché non ho la più pallida di idea di cosa vada tenuto o no

2022-06-28 11:13 UTC, leonardodemarco00 commented on src/template/ProjectsHome.tsx
> +                    link={`/progetti/${post.fieldValue.toLowerCase()}/`}
@omardeangelis Ho provato ma non mi da errori, solo i classici warnings

2022-06-28 19:11 UTC, merged