feat: create useIsMobile hook and HeaderTitle component
omardeangelis/hpv4learning pull request #202
Opened 2022-09-08 18:29 UTC by leonardodemarco00

## Done
- Creato l'hook per utilizzare isMobile
- Creato il componente per il titolo nell'header

2022-09-08 20:01 UTC, omardeangelis requested changes

2022-09-08 20:01 UTC, omardeangelis commented on src/components/modal/ModalHeader.ts
> +export const HeaderTitle = styled(Typography)`
Forse lo chiamerei ModalTitle. HeaderTitle mi da l'impressione di un componente che possa essere usato come Header in tutta un'app.

2022-09-09 09:38 UTC, leonardodemarco00 commented on src/hook/useIsMobile.ts
> +  }, [sm]);
Yes hai ragione, ma ieri al primo render mi dava problemi e l'ho risolta cosi

Ora in realtà, provando con il pc ancora fresco, questo useEffect è del tutto inutile

2022-09-09 10:51 UTC, omardeangelis approved these changes

2022-09-09 10:51 UTC, merged