feat: added udemySlice with first two methods
omardeangelis/hpv4learning pull request #284
Opened 2022-11-27 23:30 UTC by leonardodemarco00

2022-11-27 23:30 UTC, leonardodemarco00 commented
C'è qualche filippinata, domani risolvo

2022-11-28 21:49 UTC, omardeangelis requested changes
Manca la gestione degli errori furia.

2022-11-28 21:49 UTC, omardeangelis commented on src/api/udemy/get-single-course-stats-by-id.ts
> +};
Cosa succede se non ti passo req.query.id ?

2022-11-28 21:49 UTC, omardeangelis commented on src/server/udemy/index.ts
> +  return courseStats;
try catch ?

2022-11-28 21:49 UTC, omardeangelis commented on src/server/udemy/index.ts
> +  const res = await Promise.all(promisesArray);
try catch ?

2022-11-30 20:59 UTC, leonardodemarco00 commented
@omardeangelis 
Allora toro, c'è typescript che piange ma non son piu capace ad usarlo, non son riuscito a risolvere
Se riesci a dargli un occhiata tu ottimo, se no prossima volta che ci vediamo ti rompo il cazzo e mi spieghi

Ho pushato due volte lo stesso commit perchè sono leso e non avevo salvato

Per quanto riguarda gli errori ho fatto che ritornare un oggetto con l'errore ed un messaggio per i metodi ai quali bisogna passare l'id
Se intendevi altro fammi sapere che modifico

2022-11-30 21:02 UTC, leonardodemarco00 commented
Niente avevo committato roba che non doveva esserci

2022-12-02 08:10 UTC, omardeangelis commented
Hai pushato rotto

```
   8 |   baseQuery: fetchBaseQuery({
   9 |     headers: {
> 10 |       "content-type": `application/json`,,
     |                                          ^
  11 |     },
  12 |   }),
  13 |   endpoints: (builder) => ({
```

2022-12-02 16:28 UTC, merged