feat: created Guide Template Page
omardeangelis/hpv4learning pull request #305
Opened 2022-12-29 16:50 UTC by leonardodemarco00

2022-12-29 21:47 UTC, omardeangelis requested changes
Problema di responsive. 
Material UI ha come breakpoints xs, sm, md, lg, xl. Usando la scrittura `[value, value]` gli stai dicendo che fino a xs è al primo valore e da sm in poi così. Solo che `sm === 586px`

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +    width: 864px;
Ti basta usare `maxWidth: 869px` con `width: 100%` per avere il component sempre responsive

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +    width={[`73px`, `247px`]}
Anche qua da usare maxWidth: `247px` e width: 100%. Poi stringendosi il componente padre l'immagine si adatta da solo

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +              placeholder="tracedSVG"
`TracedSVG` come placeholder è stato deprecato purtroppo

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +            mr={[`unset`, `21px`]}
Non puoi usare un icona invece che un'immagine ? Come fai a colorarla ?

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +          mx={[`16px`, `unset`]}
Perché invece di impazzire con mille `mx, pl` un padding generale di `['16px', 'unset']` a questo anche un padding al container che contiene il testo e le icone ?

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +            alignItems="left"
`align: left` credo non esista

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +              width={[`unset`, `90%`]}
Anche qua, inseriscili in un box e dagli la maxWidth in px che può raggiungere e poi una width del 100%.

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/Hero.tsx
> +    height={[`508px`, `718px`]}
Metterei 100vh e fanculo

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/Hero.tsx
> +      width={[`397px`, `883px`]}
Anche qua maxWidth, altrimenti su tutti i tablet e schermi tra il 768px e i 1024 il layout si rompe

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/Hero.tsx
> +          placeholder="tracedSVG"
Anche qua, non puoi usare un'icona ?

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +    <StyledBorderBox onClick={handleNavigate}>
Qui bisogna probabilmente wrapparlo in un link in modo che google possa seguire i link e mappare le sezioni. 
Andrei anche usare la props `component='article'` sulle singole cards.

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/Hero.tsx
> +        fontSize={[`39px`, `72px`]}
da aggiungere `h1` al titolo principale e `h2` a tutti i title

2022-12-29 21:47 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +              width={[`unset`, `90%`]}
Segnerei anche come `h3` i titoli degli articoli

2022-12-30 14:25 UTC, leonardodemarco00 commented on src/feature/guide/GuideItem.tsx
> +    width: 864px;
Facendo cosi, non riesco a capire il motivo per cui me le sfasa. Alcune sono più corte ed altre più lunghe, ma solo una card (l'ultima) è della larghezza giusta.

2022-12-30 14:26 UTC, leonardodemarco00 commented
@omardeangelis risolto tutto tranne la questione della larghezza delle card scritta sopra

2022-12-30 18:18 UTC, leonardodemarco00 commented
Dio

2022-12-30 18:24 UTC, omardeangelis requested changes
@leonardodemarco00 Il problema del responsive della card è perché non hai modificato lo styledBox nel component `GuideItem.tsx`. 

Probabile che essendo wrappato da un link tu debba dare al link qualche props filippina, tipo display flex. 

Conviene ti metta dalla console a filippinare

2022-12-30 18:24 UTC, omardeangelis commented on src/feature/guide/GuideInfo.tsx
> +    gap={{ xs: `16px`, lg: `140px` }}
Gap da safari non è supportato

2022-12-30 18:24 UTC, omardeangelis commented on src/feature/guide/GuideItem.tsx
> +    height={{ xs: `41px`, lg: `140px` }}
Non penso ti serva l'altezza, l'immagine dovrebbe adattarsi mantenendo l'aspect ration

2022-12-30 20:17 UTC, leonardodemarco00 commented on src/feature/guide/GuideInfo.tsx
> +    gap={{ xs: `16px`, lg: `140px` }}
Safari mi ha rotto il cazzo

2022-12-30 20:29 UTC, omardeangelis commented
@leonardodemarco00 mancano ancora dei commit giusto ?

2022-12-30 20:29 UTC, omardeangelis commented on src/feature/guide/GuideInfo.tsx
> +    gap={{ xs: `16px`, lg: `140px` }}
Dillo a tutti quelli con un iPhone

2022-12-30 20:30 UTC, leonardodemarco00 commented
Si ho solo un attimo  maledetto safari

2023-01-01 18:16 UTC, omardeangelis requested changes
@leonardodemarco00 
Ce semo quasi. Dai un'occhiata al Figma che ti ho lasciato un commento

2023-01-01 18:16 UTC, omardeangelis commented on src/feature/guide/VideoSection.tsx
> +  width: 260px;
Fra, ti scongiuro, usa la `maxWidth` al video da desktop e `width=100%`. Da mobile maxWidth unset e via, non serve nemmeno usare l'altezza.

2023-01-02 22:38 UTC, merged