53 singolo articolo render del body dellarticolo con react markdown
omardeangelis/hpv4learning pull request #80
Opened 2022-06-15 09:27 UTC by leonardodemarco00

2022-06-15 10:14 UTC, omardeangelis requested changes
E' meglio spezzare le PR in cose più piccole, questa tra i fix e quello che manca rischia di diventare da 2000 righe aggiunte che da reviewer è davvero brutto da fare perché sei sull'editor git hub.

2022-06-15 10:14 UTC, omardeangelis commented on src/components/article/ArticleBody.tsx
> +      <ReactMarkdown children={body.body} className='markdown' />
Userei questa soluzione se no è come injectare normalmente dell'html
[render del body dellarticolo con react markdown](https://github.com/omardeangelis/hpv4learning/pull/80#)

Però avendo la PR con il mischione ti diventa di 1.200 righe

2022-06-15 10:14 UTC, omardeangelis commented on src/components/article/ArticleBody.tsx
> +  }, []);
E se l'articolo non avesse heading cosa succede ?

2022-06-15 10:14 UTC, omardeangelis commented on src/components/article/ArticleBody.tsx
> +`;
Sicuro non valga la pena rifare un componente differente ?

2022-06-15 10:14 UTC, omardeangelis commented on src/components/article/ArticleBody.tsx
> +        ></ListSection>
Se clicco sul singolo heading mi dovrebbe porta alla sezione dell'articolo di quel heading

2022-06-15 10:14 UTC, omardeangelis commented on src/components/article/LinkSection.tsx
> +);
Non c'è un componente già fatto da Material UI ?

2022-06-15 22:39 UTC, leonardodemarco00 commented
@omardeangelis ho fixato solo il render dei componenti, per il box degli headings e per l'Hero creo due issue nuove

2022-06-18 10:54 UTC, omardeangelis commented
@leonardodemarco00 
Dobbiamo mergiare as soon as possible questo. Una Pr che sta aperta per 7-8 giorni è un produttore di conflict seriale. Cerca di chiuderla perché a breve non si capirà piu nulla intorno a questa PR e le Issue correlate.

2022-06-18 12:48 UTC, merged