feat: create banner
omardeangelis/hpv4learning pull request #95
Opened 2022-06-22 10:03 UTC by leonardodemarco00

## Done
- Creato Banner sia mobile che desktop

## To Do
- Capire: I prezzi vanno passati o sono quelli fissi?
- Sistemare breakpoints in theme.js
- Capire: perchè nei componenti stilizzati con css() non mi funzionano i breakpoints.

2022-06-22 19:54 UTC, omardeangelis requested changes
Per I components prova a fare come ho fatto nel component per la project card 
```
export interface ProjectBox extends BoxProps {
  isMobileOnly?: true;
}

export const ProjectCard = styled(Box)<ProjectBox>(css({
   })
)

```

Magari si instupidisce perché non capisce che è un Box e accetta degli array. E' l'unica cosa diversa che trovo tra i due components

E si il tema è proprio da rivedere tutto gli mancano un sacco di pezzi.

2022-06-22 19:54 UTC, omardeangelis commented on src/feature/projects/components/ProjectBanner.tsx
> +                {isXl ? "riscatta il coupon" : "compra"}
Facciamo che mettere "Riscatta" in entrambi i casi

2022-06-22 19:54 UTC, omardeangelis commented on src/feature/projects/components/ProjectBanner.tsx
> +            </Stack>
Perché installare una libreria e usare un hook invece che definire uno styled component o una classe che lo nasconda sotto i 1024px ?

2022-06-22 19:54 UTC, omardeangelis commented on src/feature/projects/components/ProjectBanner.tsx
> +      {isBannerOpen ? (
Questo stato state lo andrei a mettere dentro il [context del layout](https://github.com/omardeangelis/hpv4learning/blob/main/src/context/layout.tsx) e lo userei per mostrare o non mostrare questo component, perché se no ritorna comunque un `React.Fragment` e inizializza gli styled components e runna gli hooks.

2022-06-22 19:54 UTC, omardeangelis commented on src/feature/projects/components/ProjectBanner.tsx
> +                }}
Setterei la width a 100% e usarei `maxWidth: 105px per xs e unset per lg¡

2022-06-22 19:54 UTC, omardeangelis commented on src/feature/projects/components/ProjectBanner.tsx
> +                  borderRadius: "100px",
Perché non usare la props size del tema del bottone al posto di queste props ?

2022-06-23 14:20 UTC, leonardodemarco00 commented
@omardeangelis  per la questione dei components, neanche con BoxProps funzionano 
Ma ho visto che ad esempio neanche nel componente con il bordo verde che contiene la meta description funzionano, quello tu lo vedi dritto? 
`marginTop: ["25px", "36px"], `

2022-06-24 16:09 UTC, omardeangelis requested changes

2022-06-24 16:09 UTC, omardeangelis commented on src/feature/projects/components/ProjectBanner.tsx
> +  if (isBannerOpen) {
In questo modo continua ad inizializzare styled components e hooks. Perché non usarlo nel componente padre lo state. 

`isBannerOpen ? <ProjectBanner /> : null`

2022-06-25 10:12 UTC, omardeangelis commented
@leonardodemarco00 ho risolto i conflicts, prova a pullare e vedere che non si sia spaccato nulla. 
In Generale occhio a quando lavori a PR separate che sono così comunicanti, in quei casi se si vanno ad installare packages poi l'ordine di merge è da tenere d'occhio anche rispetto a PR di altri membri del team. 

Ad esempio in questo caso avendo installato e poi rimosso dei package avevi due alternative: 
- Mergiare questa PR per prima rispetto a tutte quelle che partivano dall'ultimo state di project-sections
- Fare un rebase su questa PR in modo da risolvere i conflict in locale e poi pushare

2022-06-25 16:22 UTC, merged